# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('gallery', '__first__'),
        ('contacts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=50)),
                ('county', models.CharField(blank=True, max_length=50)),
                ('postcode', models.CharField(max_length=8)),
                ('country', models.CharField(choices=[(b'GBR', 'United Kingdom'), (b'USA', 'United States of America')], max_length=3)),
                ('description', models.TextField(blank=True)),
                ('year_built', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'permissions': (('can_undelete', 'Can undelete this object'),),
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('number', models.PositiveSmallIntegerField()),
                ('type', models.PositiveSmallIntegerField(choices=[(10, 'apartment'), (20, 'room'), (30, 'duplex'), (40, 'house'), (50, 'townhouse'), (60, 'villa'), (70, 'office'), (80, 'warehouse'), (90, 'storage'), (100, 'parking')], default=10)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('period', models.PositiveSmallIntegerField(choices=[(10, 'hourly'), (20, 'daily'), (30, 'weekly'), (40, 'every two weeks'), (50, 'monthly'), (60, 'quarterly'), (70, 'very six months'), (80, 'yearly'), (90, 'one off')], default=50)),
                ('beds', models.PositiveSmallIntegerField(choices=[(10, 'studio'), (20, '1'), (30, '2'), (40, '3'), (50, '4'), (60, '5'), (70, '6'), (80, '7'), (90, '8'), (100, '9+')], default=20)),
                ('bathrooms', models.PositiveSmallIntegerField(choices=[(10, 'shared'), (20, '1'), (30, '2'), (40, '3'), (50, '4'), (60, '5+')], default=20)),
                ('parking', models.PositiveSmallIntegerField(choices=[(10, 'None'), (20, '1'), (30, '2'), (40, '3'), (50, '4'), (60, '5+')], default=20)),
                ('description', models.TextField(blank=True)),
                ('pets', models.BooleanField(default=False)),
                ('pet_policy', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'permissions': (('can_undelete', 'Can undelete this object'),),
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='properties.UnitAttribute'),
        ),
        migrations.AddField(
            model_name='unit',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.Property'),
        ),
        migrations.AddField(
            model_name='unit',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='teams.Team'),
        ),
        migrations.AddField(
            model_name='property',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='properties.PropertyAttribute'),
        ),
        migrations.AddField(
            model_name='property',
            name='gallery',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='gallery.Gallery'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='contacts.Owner'),
        ),
        migrations.AddField(
            model_name='property',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='teams.Team'),
        ),
    ]
