# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('gallery', '0001_initial'),
        ('contacts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=50)),
                ('county', models.CharField(blank=True, max_length=50)),
                ('postcode', models.CharField(max_length=8)),
                ('country', models.CharField(choices=[(b'GBR', 'United Kingdom'), (b'USA', 'United States of America')], max_length=3)),
                ('gallery', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='gallery.Gallery')),
                ('ownder', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='contacts.Owner')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='teams.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenancy',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancies', to='properties.Property')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancies', to='teams.Team')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancies', to='contacts.Tenant')),
            ],
            options={
                'verbose_name_plural': 'Tenancies',
            },
        ),
    ]
