# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'permissions': (('can_undelete', 'Can undelete this object'),),
            },
        ),
        migrations.CreateModel(
            name='UnitAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'permissions': (('can_undelete', 'Can undelete this object'),),
            },
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='attributes',
            field=models.ManyToManyField(to='properties.PropertyAttribute'),
        ),
        migrations.AddField(
            model_name='unit',
            name='attributes',
            field=models.ManyToManyField(to='properties.UnitAttribute'),
        ),
    ]
