# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('properties', '0002_auto_20160210_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('title', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='title')),
                ('file', models.FileField(upload_to='documents', verbose_name='File')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.Property')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='teams.Team')),
            ],
            options={
                'abstract': False,
                'permissions': (('can_undelete', 'Can undelete this object'),),
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(choices=[(10, 'shared'), (20, '1'), (30, '2'), (40, '3'), (50, '4'), (60, '5+')], default=20),
        ),
        migrations.AddField(
            model_name='unit',
            name='beds',
            field=models.PositiveSmallIntegerField(choices=[(10, 'studio'), (20, '1'), (30, '2'), (40, '3'), (50, '4'), (60, '5'), (70, '6'), (80, '7'), (90, '8'), (100, '9+')], default=20),
        ),
        migrations.AddField(
            model_name='unit',
            name='deposite',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='parking',
            field=models.PositiveSmallIntegerField(choices=[(10, 'None'), (20, '1'), (30, '2'), (40, '3'), (50, '4'), (60, '5+')], default=20),
        ),
        migrations.AddField(
            model_name='unit',
            name='period',
            field=models.PositiveSmallIntegerField(choices=[(10, 'hour'), (20, 'day'), (30, 'week'), (40, 'month'), (50, 'quarter'), (60, 'year')], default=40),
        ),
        migrations.AddField(
            model_name='unit',
            name='pet_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='pets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(10, 'apartment'), (20, 'room'), (30, 'duplex'), (40, 'house'), (50, 'townhouse'), (60, 'villa'), (70, 'office'), (80, 'warehouse'), (90, 'storage'), (100, 'parking')], default=10),
        ),
    ]
