# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20160210_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
