# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20160210_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='deposite',
            new_name='deposit',
        ),
        migrations.AlterField(
            model_name='unit',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='properties.UnitAttribute'),
        ),
    ]
