# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('contacts', '0001_initial'),
        ('properties', '0006_auto_20160210_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='teams.Team')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='contacts.Tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='properties.Unit')),
            ],
            options={
                'verbose_name_plural': 'leases',
            },
        ),
        migrations.RemoveField(
            model_name='tenancy',
            name='team',
        ),
        migrations.RemoveField(
            model_name='tenancy',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='tenancy',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Tenancy',
        ),
    ]
