# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 11:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20160210_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='team',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='unit',
        ),
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
        migrations.AddField(
            model_name='document',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 11, 11, 17, 47, 159309, tzinfo=utc), verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 11, 11, 17, 58, 611751, tzinfo=utc), verbose_name='modified'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit',
            name='period',
            field=models.PositiveSmallIntegerField(choices=[(10, 'hourly'), (20, 'daily'), (30, 'weekly'), (40, 'every two weeks'), (50, 'monthly'), (60, 'quarterly'), (70, 'very six months'), (80, 'yearly'), (90, 'one off')], default=50),
        ),
        migrations.DeleteModel(
            name='Lease',
        ),
    ]
