# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('contacts', '0001_initial'),
        ('properties', '0008_auto_20160211_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('type', models.PositiveSmallIntegerField(choices=[(10, 'fixed'), (20, 'month-to-month')], default=10)),
                ('number', models.PositiveSmallIntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('period', models.PositiveSmallIntegerField(choices=[(10, 'hourly'), (20, 'daily'), (30, 'weekly'), (40, 'every two weeks'), (50, 'monthly'), (60, 'quarterly'), (70, 'very six months'), (80, 'yearly'), (90, 'one off')], default=50)),
                ('prorate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('late_payment_fee', models.BooleanField(default=False)),
                ('electric', models.NullBooleanField(default=None)),
                ('water', models.NullBooleanField(default=None)),
                ('tv', models.NullBooleanField(default=None)),
                ('garbage', models.NullBooleanField(default=None)),
                ('hoa', models.NullBooleanField(default=None)),
                ('internet', models.NullBooleanField(default=None)),
                ('council_tax', models.NullBooleanField(default=None)),
                ('landscaping', models.NullBooleanField(default=None)),
                ('gas', models.NullBooleanField(default=None)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='teams.Team')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='contacts.Tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='properties.Unit')),
            ],
            options={
                'verbose_name_plural': 'leases',
            },
        ),
        migrations.CreateModel(
            name='LeaseFees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('type', models.PositiveSmallIntegerField(choices=[(10, 'rent')], default=10)),
                ('schedule', models.PositiveSmallIntegerField(choices=[(10, 'hourly'), (20, 'daily'), (30, 'weekly'), (40, 'every two weeks'), (50, 'monthly'), (60, 'quarterly'), (70, 'very six months'), (80, 'yearly'), (90, 'one off')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('due_date', models.DateField()),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lease.Lease')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leasefees', to='teams.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
